### ISSUE TITLE
Plans to add pre-made shapes

### ISSUE THREAD

**Issue by DawidvanGraan** [webfactorymk/ng2-canvas-whiteboard#17]
Hi, 

Do you have any plans in the immediate future to add pre-made shapes to the library? 

Thanks!

**Comment by Peshou** [comment]
Hi!
Yes there are plans for adding pre-made shapes but i'm not quite sure how much time it would take to see if it will be done in the immediate future, but yes overall that is the next feature for the whiteboard.

**Comment by johannesschobel** [comment]
Dear @Peshou and community,

thank you very much for the time and effort you put into this package! Nice work!
I read about the "shape" issue and thought I may contribute with some ideas on how to deal with this issue. Please note that I am a PHP developer, so I am not aware of proper TypeScript syntax :laughing: However, you may get the idea

I propose to define an `abstract class Shape` that serves as basis for the custom shapes. This class, in turn, may look like this:

``` php
abstract class Shape {
	private $canvas;
	
	// maybe one can pass the Canvas object via Dependency Injection?
	public function __construct(Canvas $canvas) {
		$this->canvas = $canvas;
	}
	
	public function draw(EventPositionPoint $position, ShapeBoundaries $bounds, ShapeOptions $options);
}
```

At the core, it has one `draw()` method that may be implemented in respective `CustomShape` classes. Consider, for example, these 2 custom Shape classes:

``` php
class CrossShape extends Shape {
	public function draw(EventPositionPoint $position, ShapeBoundaries $bounds, ShapeOptions $options) {
		// define how to draw your custom shape here!
		$canvas->moveTo($position->x, $position->y);
		
		// draw the horizontal line
		$canvas->moveTo($position->x - ($bounds->width/2), $position->y);
		$canvas->lineTo($position->x + ($bounds->width/2), $position->y);
		
		// draw the vertical line
		$canvas->moveTo($position->x, $position->y - ($bounds->height/2));
		$canvas->lineTo($position->x, $position->y + ($bounds->height/2));
		
		$canvas->stroke();
	}
}

class RectangleShape extends Shape {
	public function draw(EventPositionPoint $position, ShapeBoundaries $bounds, ShapeOptions $options) {
		// define how to draw your custom shape here!
	}
}
```

The package, in turn, could provide some pre-defined shapes in a specific folder that may be used (e.g., a `RectangleShape`, `CircleShape`, `TriangleShape`, `StarShape`, `CrossShape`, `XShape`, ...). This may be easily extended "on demand" over time (e.g., create a new PR for each shape). Please note that this proposal is just a quick-and-dirty idea, this may be improved heavily :joy:

Further, the package may provide respective classes in order to "manipulate" the draw process, like this:

``` php 
/**
 * The center point where the user has clicked. The Shape has to be drawn "around" this point!
 **/
class EventPositionPoint {
	public $x;
	public $y;
}

/**
 * The maximum boundaries of the shape to be drawn. This may be used to "scale" the original shape
 **/
class ShapeBoundaries {
	public $width;
	public $height;
}

/**
 * Options to "influence" the visual style of the shape to be drawn
 **/
class ShapeOptions {
	public $lineColor;
	public $lineWidth;
	public $bgColor;
	// a few additional properties?!
	// this class MUST set default values for the shapes (e.g., the default color for the line, ...)
}
```

Finally, one would need to provide the `drawShape()` for the `Canvas` object.

``` php 
class Canvas {

	public function drawShape(Shape $shape, ShapeBoundaries $bounds) {
		$shape->draw($position, $bounds, $options);
	}
}
```

A user may use the new feature like this:
```
$canvas->drawShape(new RectangleShape(), new ShapeBoundaries(100, 100), new ShapeOptions(['lineColor' => 'ff0000']));
```

What do you think about this idea?!
The benefit could be, that each developer may define his own "shapes" in addition to already pre-defined ones (e.g., he could define a "Angular Logo" as `Shape` by simply extending the abstract class and then use it in his application.

Do you have any thoughts on this proposal?
All the best,
Johannes

**Comment by Peshou** [comment]
Hi, and sorry for not responding quickly enough.

Lately i had been involved in a lot of work which required my full focus and attention and had not been able to focus myself on the canvas. 

The idea is good and there should be a way that the user can extend or implement a simple interface so that he can have his custom shapes, which then in turn should be visible somewhere near the colorpicker and draw buttons.

I am still thinking about how i can change the current codebase or to refactor some things in the existing implementation, there also needs to be a way to select the shapes from the browser window and then use dragging and other mechanisms to draw the shapes on the canvas, so that part needs to be created as well.

I will try to attend to this feature as soon as i can, since after this feature i will upgrade the library for Angular 6, since i want to have backwards compatability as well (something which rxjs^6 imports are making difficult for this library at the moment).

Thank you for the thoughts and the contribution to the community, the idea is on point. I will try to implement this as soon as possible since a lot of people have a request for this feature.

**Comment by johannesschobel** [comment]
Hey @Peshou ,
thank you very much for your response on this. I fully appreciate the time you put into this project - even though you have a real job as well :laughing: 

Sadly, I am no `Angular / TypeScript` developer so I am not able to contribute to this project.. But i tried to provide some code (i know, its php :joy: ) in order to give new ideas on this topic. Maybe this will help in order to make this feature easy to extend..

All the best

**Comment by Peshou** [comment]
Okay guys,
Sorry for the long wait but version 2.0.0 with premade shapes has been published on npm. Please check it out. 
Cheers.

**Comment by johannesschobel** [comment]
oh this is awesome! thanks a lot man!
