### ISSUE TITLE
cant able to draw, using on ionic2

### ISSUE THREAD

**Issue by arunbscmdu** [WebFactoryMk/ng2-canvas-whiteboard#2]

**Comment by Peshou** [comment]
Which version of the canvas are you using? There were some problems with touch devices in older versions, but touch support was updated in version **1.1.0**.

If you are using the latest version and still have these problems, please report them again so that we can look them up

**Comment by Peshou** [comment]
An Ionic2 Demo project was created using the latest Ionic2 and angular library versions, and ng2-canvas-whiteboard@1.1.0, and the project was working when drawing on web and the web mobile device simulator

![screenshot_16](https://cloud.githubusercontent.com/assets/9078620/26766817/d5aa9092-4998-11e7-989c-24a906b6a61c.png)

The app was also started in the Android simulator, and the output was okay.
![screenshot_17](https://cloud.githubusercontent.com/assets/9078620/26767075/962bfb28-499c-11e7-9b12-ad4de24a0c5e.png)

The library was also tested on a real Android device with an Android version of 6.0. Result:
![screenshot_20170605-031329](https://cloud.githubusercontent.com/assets/9078620/26767132/3b44f86c-499d-11e7-9788-f8124be95abb.png)

As a result of these tests, please update the ng2-canvas-whiteboard version to 1.1.0 (there are no breaking changes and everything should work as it did before), and if there are issues after that please report back with more information so that we may be able to solve the issues

**Comment by Peshou** [comment]
I will close this issue for now, sorry for the inconvenience, if something happens again feel free to reopen it
