### ISSUE TITLE
Draw button disabled but drawing enabled

### ISSUE THREAD

**Issue by marcogrieco** [webfactorymk/ng2-canvas-whiteboard#20]
Hi,
there is a way to go in canvas without draw button enabled but drawing enabled. So the user doesn't must click the draw button to start the draw.

Thanks in advance.

**Comment by Peshou** [comment]
Hi, 

I currently left a backdoor method called setShouldDraw(shouldDraw: boolean): void but it's a bad idea since you must use a ViewChild reference to use this method.

I will add a drawingEnabled Input() so that u can programatically enable drawing without the user clicking the button (it will still pulsate though), which means that you can hide it as well, or if you just hate the current animation you can override it with none or another animation.

In version 1.4.4 you can find these new changes.

**Comment by Peshou** [comment]
Please check out the changes so that we can close the issue or continue working on it further

**Comment by Peshou** [comment]
Hi, the changes have been added in v1.4.5

**Comment by marcogrieco** [comment]
Thanks. Now it's ok.
