### ISSUE TITLE
Error while using with Angular 6

### ISSUE THREAD

**Issue by bhaveshvyas007** [webfactorymk/ng2-canvas-whiteboard#24]
Module not found: Error: Can't resolve 'rxjs/Subject' in '\node_modules\ng2-canvas-whiteboard\dist'.

Please help.

@angular/cli": "~6.0.5"

**Comment by Peshou** [comment]
Hi, currently angular^6 uses rxjs^6, and the imports in rxjs^6 are from "rxjs/index", so there is no backwards compatibility with the current code since rxjs 5 uses for example "rxjs/Subject". I will try to find a way to solve this issue for all Angular versions since i want this library to be compatible for everyone

**Comment by Peshou** [comment]
From what i can see there is a library for rxjs backwards compatibility and it should be available by running `npm install --save rxjs-compat` which in turn should enable all the operators to work as intended, but i will try to make a bugfix version with this lib as a peer dependency so that everyone will have it by default

**Comment by Peshou** [comment]
Version 1.4.6 adds rxjs-compat as a peer dependency but you must install peer dependencies yourself.

Please tell me if everything is okay after this change.
