### ISSUE TITLE
Load Saved "CanvasDataUrl"

### ISSUE THREAD

**Issue by sjucker** [webfactorymk/ng2-canvas-whiteboard#29]
Hi

I am using version 2.0.2.

Is it possible to "re-load" a saved CanvasDataUrl (received using generateCanvasDataUrl()) at a later point?

Or more specific: when the user presses the save-button, we store the CanvasDataUrl. At a later point it should be possible to come back to this drawing and edit it further (it is not needed to undo steps done before the saving).
Is this currently possible to achieve?

Thanks,
Stefan

**Comment by sjucker** [comment]
Hi @Peshou 

Thanks for your input.
We tried to set the imageUrl:
```

<canvas-whiteboard #canvasWhiteboard
                   [imageUrl]="'data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7'"
                   [drawButtonEnabled]="false"
                   [clearButtonEnabled]="false"
                   [undoButtonEnabled]="false"
                   [redoButtonEnabled]="false"
                   [saveDataButtonEnabled]="false"
                   [showShapeSelector]="true">
</canvas-whiteboard>
```
The image is shown in the background, however when the user draws something on the canvas, the `startingColor` is also drawn, resulting in flickering between backgound image and startingColor. Could you please take a look as to why this is the case?

Thank you.

**Comment by Peshou** [comment]
Yeah, if the canvas is not redrawn, then when dragging on premade shapes there will be an issue with multiple items being drawn instead of the dragged original. But when redrawing the canvas we need to redraw the image or the starting background.

The flicker occurs because of the loadImage method which is not synchronous, and **I also found a problem where I'm not caching the downloaded image which results in a performance issue.**

The new released version **2.0.3** should have this problem fixed where the image will not be downloaded again until it is changed and the canvas will only be redrawn with the new image and will not be cleared so the flicker won't occur. 

Please check if the changes suit your issue, or maybe we need to do something else.

**Comment by sjucker** [comment]
Tested with version 2.0.3: flickering is done. Thank you for the quick fix!

**Comment by Peshou** [comment]
No problem man,
Sorry for the inconvenience. 

I will close the issue now and we can open a new one if a problem occurs
