### ISSUE TITLE
 Optimize stroke speed

### ISSUE THREAD

**Issue by ARCHAMO** [webfactorymk/ng2-canvas-whiteboard#32]
Good morning.

The implementation has been a success. Thank you for your contribution.
But we were presented with an inconvenience when we loaded the application by means of table.
We experience undefined strokes when taking a signature.
This also happens in PC but when we write fast with the mouse.

How can I optimize the writing stroke?

**Comment by Peshou** [comment]
Hey sir,

So, the actual problem with the canvas was that it had to be redrawn when a shape is dragged since the canvas will keep it drawn, and we are not actually finished with the drawing on the shape (live drawing).

This is why there is a performance issue at the moment with the canvas and the freehand drawing had to be done without Bezier curve techniques.

The solution is to draw the shapes on a different canvas (one on the foreground with transparent colour), and when we are finished with the drawing, then we can apply it to the current canvas which will contain all drawn shapes. This will prevent the canvas from constantly redrawing and recalculating all of the shapes draw methods, and it will be a HUGE performance increase.

This change has been added and the canvas now has a version of 2.1.0.

I tested the app on a mobile android phone and it worked beautifully. Please try it yourself and give me some feedback, and if we need to figure out another action to solve this problem.

**Comment by ARCHAMO** [comment]
Good morning.
I tell you my experience Update the project with version 2.1.1 of your component, waiting for the impementation or application of brezier curves, in freehand mode but the experience was not the best.

My canvas had it inside a modal in which before opening it it changed the size programmatically and with resize it was displayed correctly in version 2.0.2, but with this new version the resize was not applied and the canvas was of a minimum width of 1.

To solve this, I put the value of aspectRatio in 1 in the properties of the canvas, with this the canvas was larger than the modal one but it was not inside.

After having already a space to write, I noticed that the strokes although if I applied the brezier effect, these were much slower than in version 2.0.2, the tests were made on PC, where before I ran normally but without brezier effect.

Thanking you for your attention. I am attentive to your help.
