### ISSUE TITLE
Shapes not work after Production Compile

### ISSUE THREAD

**Issue by KartoffelToby** [webfactorymk/ng2-canvas-whiteboard#43]
Works all fine in Dev Mode
But in Production Mode, Shapes are Selectable but still draw in strokes mode.

-> ng build --base-href=/ --prod --aot --build-optimizer --vendor-chunk=false --optimization

**Comment by Fridthjof** [comment]
Did you come up with a fix?

Currently facing the same issue.

**Comment by KartoffelToby** [comment]
@Fridthjof 
Sadly not, hoping @webfactorymk can tell us what's the problem.

**Comment by Peshou** [comment]
Basically, when the app is built with this command probably because of the minification of the code, I lose the information about which shape is selected, so because this has not happened until now, I did not know that this might happen. A fix to this is to have a string for every shape which everyone needs to override.

This issue happens because if we want to share the drawing over the internet, we need to send a signal to the recipient stating which shape is being drawn.

I will try and fix this issue now and see that I do not break any legacy code.

**Comment by Peshou** [comment]
Yeah that was the issue, each registered class for drawing shapes extends from its base class so it's minimised as the same name but with different arguments since I never actually do any checks for some concrete shape classes and work only with the base one, now I added an abstract method called getShapeName so every new shapes need to implement this and return a string, which is the name of the shape. It will probably be the same as the class name.

I will make a patch version for this update.

**Comment by Peshou** [comment]
I patched the library to v3.0.4, please check it and tell me if the problem persists.

**Comment by KartoffelToby** [comment]
Worked! Thank you

**Comment by Peshou** [comment]
Cheers, awesome, sorry for late response but got stuck in some other projects so I had my attention taken away from the library, I will close this issue for now but please open a new one if something else occurs.
