### ISSUE TITLE
ERROR in Unexpected value 'CanvasWhiteboardModule.  Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by sarathscs** [WebFactoryMk/ng2-canvas-whiteboard#6]
Hi,
I added 'CanvasWhiteboardModule' in app.module.ts. And canvas is used in one of my component. But when use 

ng serve --aot

I am getting following error.

ERROR in Unexpected value 'CanvasWhiteboardModule in C:/projectfFolder/node_modules/ng2-canvas-whiteboard/dist/ng2-canvas-whiteboard.d.ts' imported by the module 'AppModule in C:/projectfFolder/src/app/app.module.ts'. Please add a @NgModule annotation.

i domt why i am getting this error. Please suggest

**Comment by Peshou** [comment]
Hi and thank you for the report,
It seems that the library is outdated with Angular's Ahead of time Compilation.

This will be fixed with version 1.3.0.

Also, please update the @angular/compiler-cli dependency to version 1.2.4 to remove another AOT compilation problem (angular issue -> https://github.com/angular/angular-cli/issues/4551)

**Comment by Peshou** [comment]
@sarathscs  please try the building with the 1.3.0 version and tell me if there are any problems again
