### ISSUE TITLE
Options to remove Fill and shapes

### ISSUE THREAD

**Issue by jagdishcodes** [webfactorymk/ng2-canvas-whiteboard#66]
I want to remove only the fill option and certain shapes of this control. I have checked the documentation but there are no such options. I have tried using CSS and it is working fine on localhost but when I deployed this on the server certain class is not displaying. Please find the images for reference.

 I am using angular version 8

![image_2020_09_07T06_22_31_528Z](https://user-images.githubusercontent.com/18285635/92354992-ffac5700-f100-11ea-8e72-b4e2450156e9.png)
![image_2020_09_07T06_21_53_843Z](https://user-images.githubusercontent.com/18285635/92354997-033fde00-f101-11ea-9086-7f318ab30e0c.png)

**Comment by Peshou** [comment]
Hi, I've added a new version of the library: 3.1.2, so you can use that one to help your use-case.

Quick changes description:
I have exported all of the current shapes so you can unregister whichever you want by using the `CanvasWhiteboardShapeService`. Example:
```typescript
  constructor(private canvasWhiteboardShapeService: CanvasWhiteboardShapeService) {
    this.canvasWhiteboardShapeService.unregisterShapes([CircleShape, SmileyShape, StarShape, LineShape, RectangleShape]);
  }
```

I've also added 2 new inputs, `strokeColorPickerEnabled: boolean` and `fillColorPickerEnabled: boolean`, also deprecated the `colorPickerEnabled` Input().

For the sake of reverse-compat, the `colorPickerEnabled` input is still there and it will be used in combination with the two new variables. (ex: `colorPickerEnabled || fillColorPickerEnabled`). 

So for your useCase, you can use `colorPickerEnabled="false"` and `strokeColorPickerEnabled="true"`.


Also, if you want to update some of the CSS on the components, you can use the `::ng-deep` selector to pierce the component styles, or turn off the ViewEncapsulation on your own components (i do not really recommend that, since once you turn it off, the styles will forever be altered even though you may exit the screen for that component)

**Comment by jagdishcodes** [comment]
Hi Peshou, 

Thank you for your reply.  I have updated the package and now I am able to hide the fill option successfully but still, I am unable to unregister the shapes. I am receiving the following error.

![unregistershape](https://user-images.githubusercontent.com/18285635/92921464-b5550e00-f451-11ea-8c73-c3d807cb13f1.png)

**Comment by jagdishcodes** [comment]
Hi Peshou,

Thank you for your reply. I have updated the package and now I am able to hide the fill option successfully but still, I am unable to unregister the shapes. I am receiving the following error.

![unregistershape](https://user-images.githubusercontent.com/18285635/92921703-30b6bf80-f452-11ea-8e9f-588b0c1346ff.jpg)

**Comment by Peshou** [comment]
Have you imported the `CircleShape` class from the `ng2-canvas-whiteboard` package?

```typescript
import {
  CanvasWhiteboardShapeService,
  CircleShape,
} from 'ng2-canvas-whiteboard';
```

```typescript
  constructor(private canvasWhiteboardShapeService: CanvasWhiteboardShapeService) {
    this.canvasWhiteboardShapeService.unregisterShapes([CircleShape]);
  }
```

**Comment by jagdishcodes** [comment]
Oh sorry looks like Visual studio code can't able to auto-suggest this module. Thanks for the reply.
