### ISSUE TITLE
Custom font not applied before clearing the canvas

### ISSUE THREAD

**Issue by sufianetaouil** [webfactorymk/ng2-canvas-whiteboard#9]
Hi, 
I'm facing a weird issue, not sure if it concerns the package or not, but i'm stating it anyway, i'm using the canvas context to fill the canvas with some text after it loads, with a custom font, on Firefox it works perfectly as i want it, but on Chrome / Opera it load with default fault (Arial i guess) and after i click on the Clear button (I made it rewrite the text on the Onclear event) it loads with the correct font, here are my codes : 
`  ngAfterViewInit() {
    setTimeout(() => {
      this.canvas.changeColor("#000000");
      this.context = this.canvas.context;
      this.onCanvasClear();
    }, 250);

  }`
`  onCanvasClear() {
    this.drawPaperFormat();
  }`
`  drawPaperFormat() {
    this.context.lineWidth = 1;
    this.context.strokeStyle = "gray";
    for (var i = 0; i <= 1000; i += 10) {
      this.context.moveTo(i, 0);
      this.context.lineTo(i, 1000);
      this.context.moveTo(0, i);
      this.context.lineTo(1000, i);
    }
    this.context.stroke();
    this.context.font = "100px Arabic-Dots";
    this.context.fillText(this.canvasRef.nativeElement.getAttribute("content"), 100, 100);
  }`

Any ideas ?
I have another issue, not sure if i should create another ticket or not, but when i resize the browser the grids i draw using the DrawPaperFormat() are cleared and so is the contents, i added an angular listener to the resize event and have the drawPaperFormat() executed when the window resize, but it doesn't, any idea ? Thank you in advance

**Comment by Peshou** [comment]
Hi, sorry for the inconvenience.
For the first issue i used your code and i had no issue with the fonts on chrome. If by custom font you also mean system fonts, i used Verdana and the text changed accordingly.

I removed the clearing of the canvas afterViewInit, and when clicking a button to draw it still worked as intended.

For the resize, the canvas component is also listening to resize events.
By default web behavior, if the canvas dimensions are changed everything is cleared, so we then redraw the whole history of the drawn items. 
So there is maybe an issue with your listener since your method is not redrawing.
I created my own listener and it seems to work.
By using `bind` i ensure myself that "this" will contain my execution context and not the event context.
`window.addEventListener("resize", this. drawPaperFormat.bind(this));`

drawPaperFormat() {
     this.context.lineWidth = 1;
     this.context.strokeStyle = "gray";
    for (var i = 0; i <= 1000; i += 10) {
      this.context.moveTo(i, 0);
      this.context.lineTo(i, 1000);
      this.context.moveTo(0, i);
      this.context.lineTo(1000, i);
    }
    this.context.stroke();
    this.context.font = "100px Arabic-Dots";
    this.context.fillText("dsadsadsa", 100, 100);
  }

Please tell me if the resize problem still persists, but for the font problem i think i cannot reproduce the issue

**Comment by Peshou** [comment]
Grid after clicking the custom draw button (bottom left of the screen)
Arial
![screen shot 2017-10-26 at 18 55 33](https://user-images.githubusercontent.com/9078620/32046882-459aee04-ba7f-11e7-92fb-f999c03bb9bb.png)

Verdana
![screen shot 2017-10-26 at 18 55 00](https://user-images.githubusercontent.com/9078620/32046883-47567678-ba7f-11e7-9ee2-2871118c5085.png)

**Comment by sufianetaouil** [comment]
@Peshou  Thank you for your reply, the resize is working now, the font problem is something weird for custom fonts (downloaded) on chrome, you have to load the font before using it on the canvas with something like <div style="font-family: Arabic-Dots">.</div>, it has nothing to do with the package.
And thanks for the great package ! 
PS : Is there anyway to control (increase/decrease) the drawing line size ?

**Comment by Peshou** [comment]
Hi, great to hear that the problems were resolved.
No currently there is no other way to change the lineWidth from the package itself, as you saw yourself you had to do it by taking the context and changing it.
It will be done for the next update.

Cheers.
